### ISSUE TITLE
`send_message` raise `AttributeError`

### ISSUE THREAD

**Issue by DeoLeung** [cole/aiosmtplib#87]
`send_message` raise `AttributeError`

it works on `1.0.6`, failing on `1.1.0`

using official docker image `python:3.7.4`

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/faust/agents/agent.py", line 632, in _execute_task
    await coro
  File "/usr/local/lib/python3.7/site-packages/faust/agents/agent.py", line 649, in _slurp
    async for value in it:
  File "/tmp/streams/email/__init__.py", line 120, in process_message
    await smtp.send_message(msg, recipients=message['recipients'])
  File "/usr/local/lib/python3.7/site-packages/aiosmtplib/smtp.py", line 291, in send_message
    flat_message = flatten_message(message, utf8=utf8_required, cte_type=cte_type)
  File "/usr/local/lib/python3.7/site-packages/aiosmtplib/email.py", line 84, in flatten_message
    generator.flatten(message_copy)
  File "/usr/local/lib/python3.7/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/local/lib/python3.7/email/generator.py", line 195, in _write
    self._write_headers(msg)
  File "/usr/local/lib/python3.7/email/generator.py", line 418, in _write_headers
    self._fp.write(self.policy.fold_binary(h, v))
  File "/usr/local/lib/python3.7/email/policy.py", line 200, in fold_binary
    folded = self._fold(name, value, refold_binary=self.cte_type=='7bit')
  File "/usr/local/lib/python3.7/email/policy.py", line 208, in _fold
    lines = value.splitlines()
AttributeError: 'Header' object has no attribute 'splitlines'
```

**Comment by cole** [comment]
@DeoLeung can you provide more details or a sample of what the msg object looks like? The error seems to be triggered by something in the headers.

**Comment by cole** [comment]
Nevermind, I understand what is happening here.

You can avoid this problem using an `EmailMessage` and not providing a `Header` object. From [the docs](https://docs.python.org/3.7/library/email.header.html):

> This module is part of the legacy (Compat32) email API. In the current API encoding and decoding of headers is handled transparently by the dictionary-like API of the EmailMessage class. In addition to uses in legacy code, this module can be useful in applications that need to completely control the character sets used when encoding headers.

I think the stdlib docs are kind of confusing with the difference between the new (EmailMessage/Policy classes) and old (Message/Header) email APIs — also I have probably been sloppy about which one I'm referring to.

I'll work on adding compatibility for the old style, possibly with a warning.

**Comment by cole** [comment]
@DeoLeung should be fixed now in master.

**Comment by cole** [comment]
Closing as fixed; if you have any more issues, please reopen.
